### ISSUE TITLE
Will you provide processed en-ro dataset and multi-30k dataset

### ISSUE THREAD

**Issue by zhaoguangxiang** [cooelf/UVR-NMT#1]
or provide the detail data link and preprocess scripts.  They are important for replicating the results.

**Comment by cooelf** [comment]
Sorry for the late reply. I could not provide the data due to the policy of our partner institute. It is a standard process, you can easily process the data (BPE segmentation) according the description in our paper (Model Implementation part).

**Comment by Eurus-Holmes** [comment]
@cooelf EN-DE and EN-FR dataset is public, why not provide a complete pipeline to reproduce the results?

**Comment by ghost** [comment]
@cooelf I don't understand why you don't want to provide a complete pipeline to reproduce the results?

**Comment by cooelf** [comment]
Hi all, thanks for your interest. This repo is still working in progress. I just have some time for cleaning it up. It will be updated soon.

**Comment by cooelf** [comment]
Forget to reply. The full pipeline was updated two months ago.  Thanks again for your interest to this work!
