### ISSUE TITLE
Two questions about data processing

### ISSUE THREAD

**Issue by tuyunbin** [cooelf/UVR-NMT#2]
Hi, thank you for your great work. But I have two questions about data processing. 

First, when I ran prepare-wmt-en2de.sh, I got wmt17_en_de instead of wmt14_en_de. 

Second, when I ran "TEXT=wmt14_en_de
python preprocess.py --source-lang en --target-lang de --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test --destdir data-bin/wmt14_en2de --joined-dictionary --thresholdtgt 0 --thresholdsrc 0 --workers 20 DATA_DIR=data-bin/wmt14_en2de/", I got an error of 
    File "/home/zhouc/tyb/mml/1/UVR-NMT/fairseq/models/transformer_from_pretrained_xlm.py", line 12, in <module>
    from fairseq.models.transformer import (
ImportError: cannot import name 'TransformerEncoder'.  I found "fairseq.models.transformer" only has the class of TransformerAvgEncoder instead of 'TransformerEncoder'. 

So, what can I do about the above two problems. I'm looking forward to your early reply. Thank you!

**Comment by cooelf** [comment]
Hi, 

1. To use only data available in WMT'14, please use the --icml17 option. Refer to: https://github.com/pytorch/fairseq/tree/master/examples/translation. 

2. It seems that the TransformerEncoder part has been cleaned, which is the same as the original baseline implementation. I copied it back in the latest commit. Please see the update.

**Comment by tuyunbin** [comment]
Thank you very much for your quick reply. The above problems are addressed. However, another question is that  there is 'src_dict_wmt_en2ro.txt' in the 'data' directory instead of 'src_dict_wmt_en2de.txt'.

**Comment by cooelf** [comment]
The file will be generated automatically when training the model, if not existed. Please see https://github.com/cooelf/UVR-NMT/blob/master/README.md#lookup-table

**Comment by tuyunbin** [comment]
Thank you very much!
