### ISSUE TITLE
How can I compute BLEU score for the inference result?

### ISSUE THREAD

**Issue by tuyunbin** [cooelf/UVR-NMT#3]
Hi, I have got the result, i.e. "/result/wmt14_ende_test.pred". Next, how can I compute the BLEU score for this file?

**Comment by cooelf** [comment]
We used [Multi-bleu.perl](https://github.com/moses-smt/mosesdecoder/tree/RELEASE-4.0/scripts/generic/multi-bleu.perl) to compute case-sensitive 4-gram BLEU scores for all test sets after obtaining the output predictions by interactive.py. For simplicity, you can use the generate.py to get similar numbers. More details can be found in https://github.com/pytorch/fairseq.

**Comment by tuyunbin** [comment]
I have used the generate.py to compute bleu score, but the result is much lower than your result in the paper. I used the following command, i.e., python generate.py data-bin/wmt14_en2de --path checkpoints//base-wmt-en2de/checkpoint_best.pt --beam 5 --remove-bpe, and got the result that
 | Translated 3003 sentences (84224 tokens) in 14.6s (206.19 sentences/s, 5782.86 tokens/s)
| Generate test with beam=5: BLEU4 = 23.00, 54.6/28.7/17.0/10.5 (BP=1.000, ratio=1.036, syslen=66856, reflen=64506).
I used pytorch1.4.0 and a single RTX 2080Ti to implement your repo.

**Comment by cooelf** [comment]
please add `--lenpen 0.6`.

**Comment by tuyunbin** [comment]
The score has improved to 23.12 when adding --lenpen 0.6.
| Translated 3003 sentences (83267 tokens) in 14.9s (201.00 sentences/s, 5573.29 tokens/s)
| Generate test with beam=5: BLEU4 = 23.12, 54.9/28.8/17.1/10.6 (BP=1.000, ratio=1.026, syslen=66170, reflen=64506)

**Comment by tuyunbin** [comment]
Hi, when I just removed --remove-bpe, the score is 27.03
| Translated 3003 sentences (83267 tokens) in 14.7s (204.58 sentences/s, 5672.69 tokens/s)
| Generate test with beam=5: BLEU4 = 27.03, 55.7/32.8/21.5/14.6 (BP=0.983, ratio=0.983, syslen=80264, reflen=81629)
And when I removed --remove-bpe and --lenpen 0.6, the score is 
| Translated 3003 sentences (84224 tokens) in 14.7s (204.21 sentences/s, 5727.50 tokens/s)
| Generate test with beam=5: BLEU4 = 27.19, 55.3/32.6/21.4/14.5 (BP=0.995, ratio=0.995, syslen=81221, reflen=81629).

So, would you kindly provide your script for computing the score?

**Comment by cooelf** [comment]
My script is 
`CUDA_VISIBLE_DEVICES=1 python generate.py ./data-bin/wmt14_en_de --path ./checkpoints/uvr/checkpoint_best.pt --beam 5 --batch-size 512 --remove-bpe --lenpen 0.6 --quiet >> result/uvr.out`

**Comment by tuyunbin** [comment]
Hi, I used your script to compute the score, and the result is 
Translated 3003 sentences (83267 tokens) in 16.0s (187.85 sentences/s, 5208.61 tokens/s)
| Generate test with beam=5: BLEU4 = 23.12, 54.9/28.8/17.1/10.6 (BP=1.000, ratio=1.026, syslen=66170, reflen=64506).
I will debug this code these days to figure out what's wrong with it. Thank you for your help again!

**Comment by cooelf** [comment]
Did you use the provided data and the model? I just tried the evaluation from the sources in this repo, the prints are:

| [en] dictionary: 43720 types
| [de] dictionary: 43720 types
| ./data-bin/wmt14_en_de test en-de 3003 examples
| loading model(s) from uvr-sources/checkpoint/checkpoint.pt
| Translated 3003 sentences (82916 tokens) in 14.8s (202.49 sentences/s, 5591.08 tokens/s)
| Generate test with beam=5: BLEU4 = 27.91, 59.4/33.7/21.4/14.1 (BP=1.000, ratio=1.007, syslen=64977, reflen=64506)

**Comment by tuyunbin** [comment]
Yes, the result is the same as you when using your provided data and model. But the result is 28.14 in your paper, why?

**Comment by cooelf** [comment]
The BLEU score from the fairseq generate script would be slightly different from the multibleu score. And this model was roughly reproduced in my private env to avoid the risk of violating the open-source policy of my internship institute, so that it might also be slightly different from that in the paper which was trained by my co-author.

**Comment by cooelf** [comment]
It just noticed that if you train the model from scratch with one-GPU, maybe you need to set --update-freq 8. The example hyper-parameters are corresponding to 8 GPUs to converge quickly.

**Comment by tuyunbin** [comment]
OK, thank you for your quick and helpful reply.

**Comment by ilkerkesen** [comment]
@tuyunbin Do you remember that whether setting `update_freq` arg to 8 changed anything?
