### ISSUE TITLE
unrecognized arguments when running 'python train.py'

### ISSUE THREAD

**Issue by zhangliang-04** [cooelf/UVR-NMT#4]
train.py: error: unrecognized arguments: --cap2image_file data/cap2image_en2de.pickle --image_embedding_file features_resnet50/train-resnet50-avgpool.npy

**Comment by PengboLiu** [comment]
你后来解决了嘛？遇到了同样的问题。

**Comment by cooelf** [comment]
Have you installed the repo?

pip install --editable ./

**Comment by Poeroz** [comment]
> Have you installed the repo?
> 
> pip install --editable ./

Hi. I have tried this command but it doesn't seem to work. Could you give me some other advices?

**Comment by Poeroz** [comment]
I checked the **UVR-NMT/fairseq/options.py**, but did not find **--cap2image_file** and **--image_embedding_file** defined. Maybe there exist some bugs?

**Comment by mrzhang11** [comment]
I solved this issue by:

In "fairseq/models/transformer.py", uncomment the two lines:
`parser.add_argument('--cap2image_file', type=str, metavar='STR', help='cap2image_file')`  
`parser.add_argument('--image_embedding_file', type=str, metavar='STR', help='image_embedding_file')`
