### ISSUE TITLE
How to reproduce the results on wmt'14 en-de?

### ISSUE THREAD

**Issue by Poeroz** [cooelf/UVR-NMT#6]
Hi. Thanks for your great work. 

I tried to reproduce your results on wmt'14 en-de dataset but got a relatively low score. I followed the steps in README and did not modify any parameters. I trained the model on 4 GeForce RTX 2080 Ti cards. Finally I got about 26.7 on the test set, which is even lower than the transformer baseline. Could you give me some advice? Thanks!

**Comment by cooelf** [comment]
I used 8x GPUs, it seems the batch size would not be matched with 4 cards.
